# The idea is to eliminate the redundant bracket warnings on the afromInteger
# and afromRational functions only. However, this is a problem.
# No combination of hints described in:
#
# https://github.com/ndmitchell/hlint/blob/master/README.md#customizing-the-hints
#
# seems to work for the function only e.g.
#
# {-# ANN afromInteger ("HLint: ignore Redundant bracket" :: String) #-}
#
# does nothing. We also cannot attach the ANN to the class FromInteger.
#
# Somehow, writing the hints here in terms of the _class_ FromInteger
# actually works. That is, the Redundant bracket warning is ignored on
# afromInteger but nothing else. This does not appear to be documented.
#
# If we ever get a rule that allows us to ignore redundant brackets on
# constraints, use that instead.
- ignore:
    name: "Redundant bracket"
    within:
      - "Numeric.Literal.Integer.FromInteger"
      - "Numeric.Literal.Rational.FromRational"