resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/13.yaml
packages:
- .
extra-deps:
- git: https://github.com/tbidne/refined-extras.git
  commit: 4ea2733c40085529daeb1a6e7af9cab1d5c222d9
flags:
  refined:
    aeson: false
    quickcheck: false